import os

import numpy as np

from astropy.time import Time
from astropy.io.fits import Header

from astropy.wcs import WCS
import astropy.units as u
import astropy.constants as const

import warnings

from concurrent.futures import ProcessPoolExecutor
from datetime import datetime
from typing import Sequence, Tuple, Union

from tqdm import tqdm


def return_obs_info(hdrs: Sequence[Header], verbose: bool = True) -> Tuple[int, int, int, int]:
    """Return key observation dimensions from a sequence of FITS headers.

    Parameters
    ----------
    hdrs
        Sequence of FITS headers describing each exposure.
    verbose
        If ``True`` print diagnostic scan information to stdout.

    Returns
    -------
    tuple[int, int, int, int]
        Number of scan steps, measurements per step, wavelength samples, and
        spatial pixels along the slit.
    """

    if verbose:
        ## Show information on 1st and 2nd direction scanning (step size and number)
        for k in 'CNP1DSS','CNP1DNSP','CNP2DSS','CNP2DNSP',:
            print(hdrs[0][k+'*'])


    n_scan_steps = np.max(np.array([hdr['CNCURSCN'] for hdr in hdrs]))
    n_meas_at_step = np.max(np.array([hdr['CNCMEAS'] for hdr in hdrs]))

    n_wv = hdrs[0]['NAXIS1']
    n_along_slit = hdrs[0]['NAXIS2']

    return n_scan_steps, n_meas_at_step, n_wv, n_along_slit


def get_slit_coords(
    hdrs: Sequence[Header],
    output_dir: str = './outputs/'
) -> Tuple[np.ndarray, np.ndarray]:
    """Derive slit spatial coordinates and acquisition times from FITS headers.

    Parameters
    ----------
    hdrs
        Sequence of FITS headers describing each exposure.
    output_dir
        Directory where derived coordinate arrays should be stored.

    Returns
    -------
    tuple[numpy.ndarray, numpy.ndarray]
        ``hpxy_coords`` with shape ``(2, n_scan_steps, n_meas_at_step, slit_len)``
        and ``time_coords`` with shape ``(n_scan_steps, n_meas_at_step)``.
    """
    n_scan_steps = np.max(np.array([hdr['CNCURSCN'] for hdr in hdrs]))
    n_meas_at_step = np.max(np.array([hdr['CNCMEAS'] for hdr in hdrs]))

    n_alongSlit = hdrs[0]['NAXIS2']
    hpxy_coords = np.zeros((2,n_scan_steps, n_meas_at_step,n_alongSlit))
    time_coords = np.zeros((n_scan_steps, n_meas_at_step),dtype ='datetime64[ms]')

    with warnings.catch_warnings():
        warnings.simplefilter("ignore") ## TO ELIMINATE datafix warnings
        for hd in hdrs:
            wcs = WCS(hd)
            xy = wcs.array_index_to_world(0,np.arange(n_alongSlit),0)[1]
            # Extract world coordinates (Tx, Ty) and observation time along the slit.
            x,y,obstime = xy.Tx.value,xy.Ty.value,xy[0].obstime
            CNCURSCN,CNCMEAS = hd['CNCURSCN'],hd['CNCMEAS']
            hpxy_coords[0,CNCURSCN-1,CNCMEAS-1,:] = x
            hpxy_coords[1,CNCURSCN-1,CNCMEAS-1,:] = y
            time_coords[CNCURSCN-1,CNCMEAS-1] = obstime.to_datetime()

    ## Save the dataset coordinates to the location of your choice (defaults to working directory)
    ensure_directory(output_dir)
    np.save(output_dir + 'hpxy_coords.npy', hpxy_coords)
    np.save(output_dir + 'time_coords.npy', time_coords)

    print(f"Helioprojective XY Coordinates Shape: {hpxy_coords.shape}")
    print(f"Datetime Coordinates Shape: {time_coords.shape}")

    return hpxy_coords, time_coords

def get_spectral_coords(
    hdrs: Sequence[Header],
    output_dir: str = './outputs/'
) -> np.ndarray:
    """Compute the spectral dispersion axis in nanometers using WCS tools.

    Parameters
    ----------
    hdrs
        Sequence of FITS headers describing each exposure.
    output_dir
        Directory where derived spectral coordinates should be stored.

    Returns
    -------
    numpy.ndarray
        Array of spectral coordinates (in nm) corresponding to detector pixels.

    Notes
    -----
    The dispersion axis is not strictly linear (``CTYPE1`` is ``AWAV-GRA``), so the
    WCS transformation is used to produce physically meaningful coordinates.
    """
    with warnings.catch_warnings():
        warnings.simplefilter("ignore") # TO ELIMINATE datafix warnings
        wcs = WCS(hdrs[0])
        nwv = hdrs[0]['NAXIS1']
        spec_coords = wcs.array_index_to_world(0,0,np.arange(nwv))[0].to(u.nm).value

    # Save the dataset coordinates (defaults to working directory)
    ensure_directory(output_dir)
    np.save(output_dir + 'spec_coords.npy',spec_coords)
    print(f"Spectral Coordinates Shape: {spec_coords.shape}")

    return spec_coords

def get_slit_samp(
    hpxy_coords: np.ndarray,
    n_scan_steps: int,
    verbose: bool = True
) -> Tuple[float, float]:
    """Determine the raster slit step size and sampling along the slit.

    Parameters
    ----------
    hpxy_coords
        Array of helioprojective coordinates generated by :func:`get_slit_coords`.
    n_scan_steps
        Number of scan steps in the raster sequence.
    verbose
        If ``True`` print the derived sampling values to stdout.

    Returns
    -------
    tuple[float, float]
        Sampling along the slit (arcsec per pixel) and raster step size (arcsec).

    Notes
    -----
    The computed sampling incorporates any WCS ``PC_ij`` matrix transformations,
    providing an accurate physical spacing.
    """

    if n_scan_steps<=1:
        step_width = 0.
        slit_samp = np.sqrt((hpxy_coords[0,0,0,1]-hpxy_coords[0,0,0,0])**2 + (hpxy_coords[1,0,0,1]-hpxy_coords[1,0,0,0])**2 )
    else:
        step_width = np.sqrt((hpxy_coords[0,1,0,0]-hpxy_coords[0,0,0,0])**2 + (hpxy_coords[1,1,0,0]-hpxy_coords[1,0,0,0])**2 )
        slit_samp = np.sqrt((hpxy_coords[0,0,0,1]-hpxy_coords[0,0,0,0])**2 + (hpxy_coords[1,0,0,1]-hpxy_coords[1,0,0,0])**2 )
    
    if verbose:
        print(f'Raster step size in arcsec: {step_width}')
        print(f'Sampling along the slit (arcsec per pixel): {slit_samp}')

    return slit_samp, step_width


def _get_sc_mp(
    header_str: str,
    n_alongSlit: int,
    i: int
) -> Tuple[int, int, np.ndarray, np.ndarray, datetime]:
    """Reconstruct WCS from a header string and extract slit coordinates.

    The ``i`` index is included to preserve ordering from :func:`enumerate` but is
    otherwise unused.
    """
    header = Header.fromstring(header_str,sep="\n")

    with warnings.catch_warnings():
        warnings.simplefilter("ignore") # TO ELIMINATE datafix warnings
        wcs = WCS(header)
        print(wcs)
        xy = wcs.array_index_to_world(0,np.arange(n_alongSlit),0)[1]
        print(type(xy[0]))
        print(type(xy[1]))
        x,y,obstime = xy.Tx.value,xy.Ty.value,xy[0].obstime
        print('x', x)
    return header['CNCURSCN'],header['CNCMEAS'],x,y, obstime.to_datetime()


def _unpack_and_run(args: Tuple[str, int, int]) -> Tuple[int, int, np.ndarray, np.ndarray, datetime]:
    """Unpack tuple arguments and invoke :func:`_get_sc_mp`."""
    return _get_sc_mp(*args)


def get_slit_coords_mp(
    hdrs: Sequence[Header],
    cpu_max: int =4,
    output_dir: str ='./outputs/'
) -> Tuple[np.ndarray, np.ndarray]:
    """Extract slit coordinates from FITS headers using multiprocessing.

    Parameters
    ----------
    hdrs
        Sequence of FITS headers describing each exposure.
    cpu_max
        Upper bound on the number of worker processes to spawn.
    output_dir
        Directory where derived coordinate arrays should be stored.

    Returns
    -------
    tuple[numpy.ndarray, numpy.ndarray]
        Multiprocessed equivalents of the ``hpxy_coords`` and ``time_coords``
        arrays described in :func:`get_slit_coords`.
    """

    n_scanSteps = np.max(np.array([hdr['CNCURSCN'] for hdr in hdrs]))
    n_measAtStep = np.max(np.array([hdr['CNCMEAS'] for hdr in hdrs]))
    n_alongSlit = hdrs[0]['NAXIS2']
    hpxy_coords = np.zeros((2,n_scanSteps,n_measAtStep,n_alongSlit))
    time_coords = np.zeros((n_scanSteps,n_measAtStep),dtype ='datetime64[ms]')

    # Serialize headers to strings (fully picklable) 
    # Prepare list of (header_str, n_alongSlit) tuples
    tasks = [(hdr.tostring(sep="\n",padding=False, endcard=True), n_alongSlit,i) for i,hdr in enumerate(hdrs)]

    ncpus = min(os.cpu_count() , cpu_max)
    with ProcessPoolExecutor(max_workers=ncpus) as executor:
        results = list(tqdm(executor.map(_unpack_and_run, tasks),
                                     total=len(hdrs), desc="Processing"))

        for res in results:
            CNCURSCN,CNCMEAS,x,y,obstime = res
            hpxy_coords[0,CNCURSCN-1,CNCMEAS-1,:] = x
            hpxy_coords[1,CNCURSCN-1,CNCMEAS-1,:] = y
            time_coords[CNCURSCN-1,CNCMEAS-1] = obstime
    
    # Save the dataset coordinates (defaults to working directory)
    ensure_directory(output_dir)
    np.save(output_dir + 'hpxy_coords.npy',hpxy_coords)
    np.save(output_dir + 'time_coords.npy',time_coords)

    print(f"Helioprojective XY Coordinates Shape: {hpxy_coords.shape}")
    print(f"Datetime Coordinates Shape: {time_coords.shape}")

    return hpxy_coords, time_coords

def calculate_cadence(tc: np.ndarray, plot_cad: bool = False) -> float:
    """Estimate the median cadence of observations in seconds.

    Parameters
    ----------
    tc
        Array of acquisition timestamps as produced by :func:`get_slit_coords`.
    plot_cad
        If ``True`` plot and save the cadence series using :mod:`matplotlib`.

    Returns
    -------
    float
        Median cadence in seconds between successive exposures.
    """
    tc = tc.squeeze()

    # Differences between successive timestamps expressed in seconds.
    cad = [ (tc[i]-tc[i-1]).item().total_seconds() for i, _ in enumerate(tc)]
    med_cad = np.median(cad[1:])

    if plot_cad:
        plt.plot(cad[1:], '.')
        plt.xtitle('Frames')
        plt.ytitle('Seconds')
        plt.savefig('cadence_values.png')

    return med_cad

def shift_to_v(
    delta_lam: np.ndarray,
    lam_0: float = 1074.7,
    lam_cor: float = 0.7
) -> u.Quantity:
    """Convert wavelength shifts to Doppler velocities in km/s.

    Parameters
    ----------
    delta_lam
        Array of measured wavelength offsets.
    lam_0
        Rest wavelength (nm) of the observed spectral line.
    lam_cor
        Empirical correction applied to the measured wavelength shifts.
    """
    c_km_s = const.c.to(u.km/u.s)
     # correction to measured shifts (from fitting procedure)
    F = (delta_lam-lam_cor)/lam_0-1
    return (F**2-1)/(F**2+1)*c_km_s # Doppler formula


def calc_ntlw(
    data: np.ndarray,
    res_pow: float,
    wave: float = 1074.7,
    v_th: Union[float, Sequence[float], np.ndarray] = 21.0
) -> u.Quantity:
    """Calculate non-thermal line widths for a spectral line.

    Parameters
    ----------
    data
        Observed full-width-half-maximum (FWHM) values in nanometers.
    res_pow
        Instrument resolving power.
    wave
        Central wavelength (nm) of the observed spectral line.
    v_th
        Thermal velocity (km/s). May be scalar or broadcastable array.

    Returns
    -------
    astropy.units.Quantity
        Non-thermal line width expressed in km/s.
    """

    if np.ndim(v_th) == 0:
       v_th = np.full_like(data, v_th)

    elif isinstance(v_th, (list, tuple, np.ndarray)):
        v_th = np.asarray(v_th)
        if v_th.shape != data.shape:
            raise ValueError(f"`v_th` must be either a scalar or the same shape as `data` (got {v_th.shape}, expected {data.shape})")

    v_th = v_th *u.km/u.s # km/s
    fac = 2*np.sqrt(np.log(2))
    w_i = wave*u.nm /res_pow # nm
    scale = wave*u.nm/ const.c.to(u.nm/u.s)

    fwhm = np.sqrt(2)*fac*data*u.nm # nm
    ntlw = np.sqrt((fwhm**2-w_i**2)/scale**2/fac**2-v_th.to(u.nm/u.s)**2)

    return ntlw.to(u.km/u.s)


def ensure_directory(directory_path: str) -> None:
    """Create *directory_path* if it does not already exist."""
    if not os.path.exists(directory_path):
        os.makedirs(directory_path)
        print(f"Directory created: {directory_path}")
    else:
        print(f"Directory already exists: {directory_path}")

def which_line(spec_coords: np.ndarray, verbose: bool = True) -> Tuple[float, int, int]:
    """Return the central wavelength and indices for the line and continuum pixels."""

    if (1074.65 > spec_coords.min()) and (1074.65 < spec_coords.max()):
        wv_cen = 1074.65  # wavelength center of targeted coronal Fe XIII line
        # pixel location of coronal line
        wv_line = np.argmin(np.abs(spec_coords - 1074.65))
        wv_cont = np.argmin(np.abs(spec_coords - 1074.0))  # pixel location of clean continuum
    elif (1079.8 > spec_coords.min()) and (1079.8 < spec_coords.max()):

        wv_cen = 1079.8  # wavelength center of targeted coronal Fe XIII line
        wv_line = np.argmin(np.abs(spec_coords - 1079.8))  # pixel location of coronal line
        wv_cont = np.argmin(np.abs(spec_coords - 1080.2))  # pixel location of clean continuum
    else:
        print('Wavelength case not handled ye')
        raise

    if verbose:
        print(f"Coronal line nominal center wavelength [nm]: {wv_cen}")
        print(f"Spectral pixel index for coronal line: {wv_line}")
        print(f"Spectral pixel index for continuum reference: {wv_cont}")

    return wv_cen, wv_line, wv_cont
    
def print_exposure(hdrs: Sequence[Header]) -> None:
    """Pretty-print key exposure-related FITS header values.

    Parameters
    ----------
    hdrs
        Sequence of FITS headers; only the first header is used for printing.
    """
    exposureKeys = ['XPOSURE','TEXPOSUR','CAM_FPS','CNNSCI','CNNNDR','CNMODNST','CNNMEAS']
    for key in exposureKeys:
        print(f"{key.ljust(10)} {hdrs[0].comments[key].ljust(25)} {hdrs[0][key]} ")
    print(f"Time between ramps (i.e. triggers): {1./hdrs[0]['CAM_FPS']*1000.} msec")
    print(f"Times between first and last trigger: {Time(hdrs[-1]['DATE-AVG']).to_datetime() -Time(hdrs[0]['DATE-AVG']).to_datetime()}")